import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/* Header */}
          {/* <Header/> */}
          <main className="min-h-screen">{children}</main>
          {/* Footer */}
          <footer className="bg-neutral-500/30 py-10 text-center">
            <div className="container mx-auto px-4 py-2 text-center bg-muted-foreground">
              <p className="font-bold text-neutral-800">
                Made by Priyanshu Dhawan
              </p>
            </div>
            <p className="text-sm font-serif">2025 Terms and Conditions ©</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
